### ISSUE TITLE
conda env create --file text2mesh.yml does not work :(

### ISSUE THREAD

**Issue by HyperStudio-2020** [threedle/text2mesh#16]
I have anaconda correctly installed, I have an RTX3090 but the conda command just does not work :(

**Comment by HyperStudio-2020** [comment]
Here the error log: it fails when installing pip dependencies

[TEXT2MESH_ERROR_LOG.txt](https://github.com/threedle/text2mesh/files/8383322/TEXT2MESH_ERROR_LOG.txt)

**Comment by factoryofthesun** [comment]
Hi we've recently updated the yaml file. Could you try installing the environment with the new version?

**Comment by bruno1308** [comment]
Did you manage to get it to work @HyperStudio-2020? I'm having the same issue here (freshly cloned main branch)

**Comment by EadmondDai** [comment]
I am also having issue installing the env.
Trying this on wsl2 unbuntu 22.04. Here is the log:

conda env create --file text2mesh.yml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/ead/anaconda3/envs/text2mesh/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ead/Github/text2mesh/condaenv.s4s6kdc0.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 (from -r /home/ead/Github/text2mesh/condaenv.s4s6kdc0.requirements.txt (line 1))
  Cloning https://github.com/openai/CLIP.git (to revision d50d76daa670286dd6cacf3bcd80b5e4823fc8e1) to /tmp/pip-req-build-n21spa_n
Collecting git+https://github.com/NVIDIAGameWorks/kaolin@a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98 (from -r /home/ead/Github/text2mesh/condaenv.s4s6kdc0.requirements.txt (line 2))
  Cloning https://github.com/NVIDIAGameWorks/kaolin (to revision a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98) to /tmp/pip-req-build-a7xivjj4

Pip subprocess error:
  Running command git clone -q https://github.com/openai/CLIP.git /tmp/pip-req-build-n21spa_n
  Running command git rev-parse -q --verify 'sha^d50d76daa670286dd6cacf3bcd80b5e4823fc8e1'
  Running command git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git checkout -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git clone -q https://github.com/NVIDIAGameWorks/kaolin /tmp/pip-req-build-a7xivjj4
  Running command git rev-parse -q --verify 'sha^a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98'
  Running command git fetch -q https://github.com/NVIDIAGameWorks/kaolin a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98
  Running command git checkout -q a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /home/ead/anaconda3/envs/text2mesh/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-a7xivjj4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-a7xivjj4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ngo3m38i
         cwd: /tmp/pip-req-build-a7xivjj4/
    Complete output (13 lines):
    /tmp/pip-req-build-a7xivjj4/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      from pkg_resources import parse_version
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-a7xivjj4/setup.py", line 31, in <module>
        import torch
      File "/home/ead/anaconda3/envs/text2mesh/lib/python3.9/site-packages/torch/__init__.py", line 201, in <module>
        _load_global_deps()
      File "/home/ead/anaconda3/envs/text2mesh/lib/python3.9/site-packages/torch/__init__.py", line 154, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/home/ead/anaconda3/envs/text2mesh/lib/python3.9/ctypes/__init__.py", line 374, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/ead/anaconda3/envs/text2mesh/lib/python3.9/site-packages/torch/lib/../../../../libcublas.so.11: undefined symbol: cublasLtBIIMatmulAlgoGetHeuristic, version libcublasLt.so.11
    ----------------------------------------
WARNING: Discarding git+https://github.com/NVIDIAGameWorks/kaolin@a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

failed

CondaEnvException: Pip failed

Tried to udpate the pip in the base env, didn't work
