### ISSUE TITLE
Error in Cell # 5 of Colab notebook

### ISSUE THREAD

**Issue by metaphorz** [threedle/text2mesh#7]
I took the jupyter notebook from a Kaggle notebook and it ran fine until cell 5.
Here is the error:
<img width="1316" alt="Screen Shot 2022-01-06 at 11 56 38 AM" src="https://user-images.githubusercontent.com/3519631/148428714-b5cb46a9-945d-435e-9f78-394491a73cc6.png">

**Comment by stan-bondarenko** [comment]
What is your PyTorch version? Try using 1.9.0
`pip install torch==1.9.0`

**Comment by metaphorz** [comment]
The default for Google Colab is: torch-1.10.0+cu111 so I installed 1.9.0 as suggested. I seem to get the same error: Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import kaolin.ops.mesh
  File "/usr/local/lib/python3.7/dist-packages/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/usr/local/lib/python3.7/dist-packages/kaolin/io/__init__.py", line 5, in <module>
    from . import render
  File "/usr/local/lib/python3.7/dist-packages/kaolin/io/render.py", line 8, in <module>
    from ..render.camera import generate_perspective_projection
  File "/usr/local/lib/python3.7/dist-packages/kaolin/render/__init__.py", line 2, in <module>
    from . import mesh
  File "/usr/local/lib/python3.7/dist-packages/kaolin/render/mesh/__init__.py", line 1, in <module>
    from .utils import *
  File "/usr/local/lib/python3.7/dist-packages/kaolin/render/mesh/utils.py", line 21, in <module>
    from ... import ops
  File "/usr/local/lib/python3.7/dist-packages/kaolin/ops/__init__.py", line 1, in <module>
    from . import batch
  File "/usr/local/lib/python3.7/dist-packages/kaolin/ops/batch.py", line 16, in <module>
    from kaolin import _C
ImportError: /usr/local/lib/python3.7/dist-packages/kaolin/_C.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_

**Comment by rawwerks** [comment]
I got the exact same error when trying to port from Kaggle to Colab. 

For what it's worth, I also tried installing conda on the Colab instance and using "conda activate text2mesh" as instructed in the GitHub repo readme, which did not appear to load CLIP correctly:

```

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import clip
ModuleNotFoundError: No module named 'clip'

```

**Comment by Chauban** [comment]
> I got the exact same error when trying to port from Kaggle to Colab.
> 
> For what it's worth, I also tried installing conda on the Colab instance and using "conda activate text2mesh" as instructed in the GitHub repo readme, which did not appear to load CLIP correctly:
> 
> ```
> 
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     import clip
> ModuleNotFoundError: No module named 'clip'
> ```

Did you solve this error please?

**Comment by mfrashad** [comment]
Hi I faced the same issue and managed to fix it by following the Kaolin docs on its installation. You can see my fix on  #17 and here is my [notebook
](https://colab.research.google.com/github/mfrashad/text2mesh/blob/main/colab_demo.ipynb).

First install a compatible pytorch, and cython version and other dependencies.
```
!pip install trimesh==3.9.33 einops==0.3.2 scipy==1.5.2 \
             siren-pytorch==0.1.5 usd-core==21.8 \
             torch==1.9.0 torchtext==0.10.0 torchvision==0.10.0 cython==0.29.20 \
             git+https://github.com/openai/CLIP.git@04f4dc2ca1ed0acc9893bd1a3b526a7e02c4bb10 \

```

Then install kaolin by doing this.
```
!git clone --recursive https://github.com/NVIDIAGameWorks/kaolin
%cd kaolin
!git checkout v0.10.0
!python setup.py develop
%cd ..
```

**Comment by mothormothormothor** [comment]
I have a Colab error with the first codeblock. The error only says

ERROR: Invalid requirement: '\\'

no further information is given. I continued with the notebook and at somepoint CLIP is missing. Any suggestion on how to solve this ?
